### ISSUE TITLE
Does it support yarn@berry

### ISSUE THREAD

**Issue by wood1986** [streamich/fs-monkey#208]
1. go and `git clone https://github.com/wood1986/fs-monkey-bugs.git`
2. compare the output of `./yarn1.sh` and `./yarn2.sh`

./yarn1.sh can run without error and output
```
Hello from memfs.log.js
Hello from fs.log.js
```

./yarn2.sh can output
```
Error: Qualified path resolution failed - none of the candidates can be found on the disk.

Source path: /memfs.log.js
Rejected candidate: /memfs.log.js
Rejected candidate: /memfs.log.js.js
Rejected candidate: /memfs.log.js.json
Rejected candidate: /memfs.log.js.node
```

I cannot identify if it is yarn@berry issue or fs-monkey

**Comment by G-Rath** [comment]
Closing since this was a bug with Yarn berry
