### ISSUE TITLE
rm and rmSync don't work on a patched-in memfs volume

### ISSUE THREAD

**Issue by thomasperi** [streamich/fs-monkey#320]
Deleting a directory with `rm` or `rmSync` does not delete the directory when run on a memfs Volume patched in with `patchFs`.

Both methods work when using a memfs Volume directly, just not with `patchFs`.

Only the `rm` and `rmSync` methods don't work. The `rmdir` and `rmdirSync` methods seem to work as intended with `patchFs` and an memfs Volume.

fs-monkey/src/util/lists.js doesn't contain `rm` or `rmSync`. I'm not sure whether they were left out intentionally for some reason, or if their absence really is a bug.

[memfs-rm.js.txt](https://github.com/streamich/fs-monkey/files/7922575/memfs-rm.js.txt)

**Comment by G-Rath** [comment]
Yup this sounds like a bug that should hopefully be fixed by #362, however CI is currently broken so we can't publish new releases until #366 is resolved by @streamich

**Comment by larshp** [comment]
I have encountered the same problem

**Comment by G-Rath** [comment]
This has been released in v1.0.4 🎉
