### ISSUE TITLE
Incompatible with package.json export(node 14+)

### ISSUE THREAD

**Issue by fatWill** [streamich/fs-monkey#377]
I found an issue that when I use CommonJS specification (such as axios version 1.3.0 or newer), pathRequire cannot be properly required. The reason is that Axios has declared export in package.json.

<img width="389" alt="image" src="https://github.com/streamich/fs-monkey/assets/20520334/abb09f6f-5c0d-4313-b4f6-916d41e74a56">

Looking forward to your reply.

**Comment by dylannil** [comment]
PR: https://github.com/streamich/fs-monkey/pull/378

**Comment by G-Rath** [comment]
Resolved in https://github.com/streamich/fs-monkey/pull/378
