### ISSUE TITLE
Add `unpatch` method

### ISSUE THREAD

**Issue by vjpr** [streamich/fs-monkey#4]
I want to use this in tests. It would be great to have a `unpatch` method for after tests have run.

`patchFs` could return a method to unpatch.

Or maybe `patchfs(require('fs'))` will work?

**Comment by footearth** [comment]
The same requirement..
How to patchFs back to system fs
or unpatch?

**Comment by streamich** [comment]
What do you guys think about the following syntax:

```js
import {patchFs} from 'fs-monkey';
import {vol} from 'memfs';

const unpatch = patchFs(vol);

// Do your stuff...

unpatch();
```

**Comment by streamich** [comment]
I hope it works:

https://github.com/streamich/fs-monkey/releases/tag/v0.3.0

**Comment by footearth** [comment]
Thank you for the greate work first.
Pls check that the function 'unpatch' will print some debug msg use 'console.log'.

**Comment by footearth** [comment]
Now I use "postInstall" to fix it.
`"postinstall": "sed -i '/console\\.log(bkp);/d' ./node_modules/fs-monkey/lib/patchFs.js"`

**Comment by streamich** [comment]
@footearth Thanks for the find, my bad.

Fixed version coming soon.

**Comment by streamich** [comment]
https://github.com/streamich/fs-monkey/releases/tag/v0.3.1

**Comment by ndelangen** [comment]
This needs documentation
